#!/bin/sh
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PID_FILE="/usr/local/var/run/firewall/firewall-controller.pid"

DB_FILE="/usr/local/var/run/firewall/firewall_db.pid"


start_controller() {
    # Check for /usr/local/var/run/firewall/firewall-controller.pid 
    # If exist print message already running and exit 
    if [ -f "$PID_FILE" ]; then
            echo "Firewall controller is already running. PID file exists at $PID_FILE."
            exit 0
    fi

    echo "Starting the firewall controller..."
    firewall-controller -vconsole:emer -vsyslog:err -vfile:info --no-chdir --log-file=/usr/local/var/log/firewall/firewall-controller.log --pidfile=/usr/local/var/run/firewall/firewall-controller.pid --detach --monitor

    # Save the PID of the running process to the PID file
    echo "Firewall controller started with PID $(cat $PID_FILE)."
}

stop_controller() {
    echo "Stopping the firewall controller..."

    # Check if the PID file exists
    if [ ! -f "$PID_FILE" ]; then
        echo "No PID file found. Firewall controller might not be running."
        exit 1
    fi

    # Kill the process using the PID and remove the PID file
    PID=$(cat "$PID_FILE")
    if kill -9 "$PID" &>/dev/null; then
        echo "Firewall controller (PID $PID) stopped."
        rm -f "$PID_FILE"
    else
        echo "Failed to stop firewall controller. Check the process manually."
    fi
}

command=$1 

case "$command" in
    start_controller)
        start_controller
        ;;
    stop_controller)
        stop_controller
        ;;
    *)
        echo "Usage: $0 {start_controller|stop_controller}"
        exit 1
        ;;
esac
